services:
  sai-storage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8880:8880
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
